Repository cgq-qgc/HydroSensorReader, pull requests merged in 2018-11, with the labels that each got.

#24 PR: Add a .coveragerc file to exclude testing code from coverage analysis
  .coveragerc
Labels: enhancement

#23 PR: Load Solinst data file automatically by default.
  .travis.yml
  hydsensread/file_parser/concrete_file_parser.py
  hydsensread/file_reader/abstract_file_reader.py
  hydsensread/file_reader/compagny_file_reader/solinst_file_reader.py
  hydsensread/tests/files/2XXXXXX_solinst_levelogger_edge_testfile.csv
  hydsensread/tests/files/2XXXXXX_solinst_levelogger_edge_testfile.xle
  hydsensread/tests/test_solinst_reader.py
  requirements-dev.txt
Labels: enhancement

#25 Update Master Branch
  .coveragerc
  .travis.yml
  LICENSE
  LICENSE.txt
  hydsensread/file_parser/concrete_file_parser.py
  hydsensread/file_reader/abstract_file_reader.py
  hydsensread/file_reader/compagny_file_reader/solinst_file_reader.py
  hydsensread/tests/files/2XXXXXX_solinst_levelogger_edge_testfile.csv
  hydsensread/tests/files/2XXXXXX_solinst_levelogger_edge_testfile.xle
  hydsensread/tests/test_solinst_reader.py
  requirements-dev.txt
Labels: enhancement

#28 PR: Fix reading data level and baro data files from gold solinst loggers
  bandit.yml
  hydsensread/file_reader/compagny_file_reader/solinst_file_reader.py
  hydsensread/tests/files/1XXXXXX_solinst_levelogger_gold_testfile.csv
  hydsensread/tests/files/1XXXXXX_solinst_levelogger_gold_testfile.lev
  hydsensread/tests/files/2XXXXXX_solinst_levelogger_edge_testfile.lev
  hydsensread/tests/test_solinst_reader.py
Labels: bug, status: ready for review, test:file-reader

#29 PR: Update coveralls badge
  docs/README.md
Labels: enhancement, status: ready for review

#31 Strip units in Solinst csv reader for the 1xxxxxx series
  hydsensread/file_reader/compagny_file_reader/solinst_file_reader.py
  hydsensread/tests/test_solinst_reader.py
Labels: bug, status: ready for review
